version: '3.2'
services:
  web:
    build: .
    command: mix phx.server
    links:
      - db
    volumes:
      - .:/work
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
    volumes:
      - db:/var/lib/postgresql/data
  data:
    image: busybox
    volumes:
      - db:/var/lib/postgresql/data
      - bundle:/usr/local/bundle
volumes:
  db:
    driver: local
  bundle:
    driver: local